```{# Are accidents caused more by certain demographics? Gender, age, income}
# 
# Are accidents caused more by certain types of cars?
# 
# Are accidents happening more at certain times of the day? Divide day into 3 hr windows maybe
# 
# Are accidents happening more in certain areas of the streets? Intersections, freeways, regular portion of the streets? And what speed limit zones?
# 
# What % are caused due to speeding? Any other reason stands out?
# 
# How many cars on average ( daily /monthly/ annually ) get involved in accidents ( responsible or not )
# 
# Is there any trend where and what times - multiple car ( 3 or more cars ) accidents happen?
# 
# How many accidents are single car accidents? What are the main causes?





{r}

#install.packages("readr")
library(readr)
library(dplyr)

getwd()

traffic <- read.csv("Project_Code/Data/data_traffic.csv")


traffic

```

```{r}
## Visualizing some basic data

library(ggplot2)


#By month
ggplot(data = traffic, aes(x=month)) + geom_bar()


#By year
ggplot(data = traffic, aes(x=accident_year)) + geom_bar()


#By gender
pie(table(traffic$party_sex))


#Injury types
pie(table(traffic$collision_severity))


#Time of day

pie(table(traffic$time_cat))


```

```{r}
## This will only focus on who caused accidents

accidenters <- subset(traffic, at_fault == "Yes")

#head(accidenters)




#by_age <- subset(accidenters, !is.na(party_age))
#by_age <- subset(by_age, party_age > 15)      

by_age <- filter(accidenters, party_age > 0)

#by_age

##Histogram by age and subdivided by gender
ggplot(data = by_age, aes(x=party_age, fill = factor(party_sex))) + geom_histogram()
```
