Reading the data

```{r}
traffic_data <- read.csv("data_traffic.csv")
nrow(traffic_data)
```

Remove NA values and subset data

```{r}
install.packages("janitor")
library(janitor)
library(dplyr)
library(ggplot2)
#remove NA values and subset data
cleaned_data <- traffic_data |>
  select("party_age", "at_fault") |>
  na.omit()
#plot data
cleaned_data |>
  filter(at_fault == "Yes") |>
  ggplot(aes(x = party_age)) + geom_histogram(fill = "grey", boundary = 0) +
  labs(title = "Distribution of Ages for At-Fault Parties",
       x = "Age of Party",
       y = "Count") +
  xlim(0,100) +
  ylim(0, 1600)
cleaned_data |>
  filter(at_fault == "No") |>
  ggplot(aes(x = party_age)) + geom_histogram(fill = "grey", boundary = 0) + labs(title = "Distribution of Ages for Non-Fault Parties",
       x = "Age of Party",
       y = "Count") + 
  xlim(0,100) +
  ylim(0,1600)
```

Find factors that could cause these higher crash rates from mid aged people.

```{r}

sobriety_data <- traffic_data |>
  filter(party_age  > 0) |>
  select("party_age", "party_sobriety") |>
  na.omit()
table(sobriety_data$party_sobriety)
sobriety_data |>
  filter(party_sobriety == "Had Been Drinking, Under Influence") |>
  ggplot(aes(x = party_age)) + geom_histogram(fill = "grey", boundary = 0) + labs(title = "Distribution of Ages for Under the Influence Drinking crashes",
       x = "Sobriety",
       y = "Count") + 
  xlim(0,100) + 
  ylim(0, 70)
sobriety_data |>
  filter(party_sobriety == "Had Not Been Drinking") |>
  ggplot(aes(x = party_age)) + geom_histogram(fill = "grey", boundary = 0) + labs(title = "Distribution of Ages for No Drinking crashes",
       x = "Sobriety",
       y = "Count")
```

Fit a model to predict a party's sobrety
